services:

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: levantos
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscription
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  app:
    container_name: subscription
    build: .
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8080:8080"
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: